// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolSubjects.Infrastructure;

#nullable disable

namespace SchoolSubjects.Infrastructure.Migrations
{
    [DbContext(typeof(SchoolContext))]
    partial class SchoolContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolSubjects.Domain.Literature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("Literature");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SubjectId = 1,
                            Title = "Mathematics for Beginners"
                        },
                        new
                        {
                            Id = 2,
                            SubjectId = 1,
                            Title = "Advanced Algebra"
                        },
                        new
                        {
                            Id = 3,
                            SubjectId = 2,
                            Title = "Shakespeare's Sonnets"
                        },
                        new
                        {
                            Id = 4,
                            SubjectId = 2,
                            Title = "Modern English Grammar"
                        },
                        new
                        {
                            Id = 5,
                            SubjectId = 3,
                            Title = "The Art Book"
                        },
                        new
                        {
                            Id = 6,
                            SubjectId = 3,
                            Title = "Drawing on the Right Side of the Brain"
                        });
                });

            modelBuilder.Entity("SchoolSubjects.Domain.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfWeeklyClasses")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Mathematics focuses on numbers and problem-solving.",
                            Name = "Math",
                            NumberOfWeeklyClasses = 5
                        },
                        new
                        {
                            Id = 2,
                            Description = "English covers literature, writing, and grammar.",
                            Name = "English",
                            NumberOfWeeklyClasses = 4
                        },
                        new
                        {
                            Id = 3,
                            Description = "Art encourages creativity through drawing and painting.",
                            Name = "Art",
                            NumberOfWeeklyClasses = 2
                        });
                });

            modelBuilder.Entity("SchoolSubjects.Domain.Literature", b =>
                {
                    b.HasOne("SchoolSubjects.Domain.Subject", null)
                        .WithMany("LiteratureUsed")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolSubjects.Domain.Subject", b =>
                {
                    b.Navigation("LiteratureUsed");
                });
#pragma warning restore 612, 618
        }
    }
}
